#!/usr/bin/env python3
# This line tells a computer to interpret (i.e., run) the program using python3 (aka python on CS50 IDE), an interpreter that understands Python 3.

import os
import sys

from analyzer import Analyzer # import a class called Analyzer from a module called analyzer
from termcolor import colored # import a function called colored from a package called termcolor
# a class in Python is like a struct in C except that a class can also contain functions, otherwise known as "methods" when they’re inside a class

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile word")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives) # instatiate (allocate) an Analyzer object

    # analyze word
    score = analyzer.analyze(sys.argv[1]) # pass to that object’s analyze method the word that a user has provided in sys.argv[1]
    if score > 0.0:
        print(colored(":)", "green"))
    elif score < 0.0:
        print(colored(":(", "red"))
    else:
        print(colored(":|", "yellow"))
    # the method will return a positive int if its input is positive, a negative int if its input is negative, and 0 if its input is neither positive nor negative.


if __name__ == "__main__":
    main()
